version: '3.8'

services:
  db:
    image: postgres:15
    container_name: school_event_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: school_event
    ports:
      - "5432:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
